### ISSUE TITLE
[BUG] Don't remove from MangaDex reading list if not in SyncDex list

### ISSUE THREAD

**Issue by cpiber** [Glagan/SyncDex#1]
Currently when a title is not in my SyncDex reading list but I directly open a chapter, it tells me that the status on MangaDex has been updated (it is removed from my lists). It then asks me if I want to update, and if so adds it back. The problem is that after that, MangaDex loses all my read chapter information. The extension should never remove a title, especially not since with the migration from MyMangaDex to SyncDex many titles not on MyAnimeList aren't in the SyncDex database (since apparently importing these titles does not work at all).

**Comment by Glagan** [comment]
Hum, that's a problem, I'll look at that.

The *SyncDex database* (mochi) to convert Titles between Services actually had a bug, a lot of MyAnimeList titles had missing names so there a lot of missing connections, I'm fixing it but it's taking some times, probably in the next few days.

**Comment by Glagan** [comment]
In the meantime you can maybe import your MyMangaDex save, then MangaDex (with the merge option) to make sure there is all titles and with names.

**Comment by cpiber** [comment]
I did import MyMangaDex, I didn't do MangaDex itself though, I'll check that.
But all of the titles I noticed it on really aren't on MAL (at least according to MD description).

**Comment by Glagan** [comment]
I actually can't reproduce this issue, with an empty save and a title already in my MangaDex list, I only get one ``MangaDex status updated`` notification, even after clicking a confirmation notification.

Is it what I'm testing, the title is not in your Local (SyncDex) save, but it's already on MyAnimeList for example, and it already has a MangaDex status ?

**Comment by cpiber** [comment]
After a bit of testing, I found out: This problem only occurs for titles imported from MyMangaDex that did not have a MAL id associated with them. Works perfectly fine for everything else.

**Comment by Glagan** [comment]
Does this still happen ? I still couldn't reproduce.

Could you post your logs (well, I only want the options) so I can see why it would happen.

**Comment by cpiber** [comment]
Doesn't happen anymore :+1:
