### ISSUE TITLE
[REQUEST] Dark mode for the " Title page SyncDex overview "

### ISSUE THREAD

**Issue by lol480phuh** [Glagan/SyncDex#10]
Exactly what the title says, since I use the dark mode for Mangadex and SyncDex I thought it'd make sense for the overview section to be dark, but it's so bright that it feels out of place.

![image](https://user-images.githubusercontent.com/52804334/103158129-e0722c00-47ba-11eb-9433-eef5e61ff3f2.png)

**Comment by Glagan** [comment]
I added a dark mode for Services that needed it (SyncDex, MyAnimeList and MangaUpdates).  
All modals should also follow your preferred color scheme and be dark if you have it set to dark.

The Overview dark mode follow your **MangaDex** theme and not your preferred color scheme, unlike modals.

**Comment by lol480phuh** [comment]
Again, thank you for your hard work Dev!! this is perfect
![image](https://user-images.githubusercontent.com/52804334/103197066-a81b3c80-48e5-11eb-968f-674e3658cc8a.png)
