### ISSUE TITLE
[BUG] Title.link is an abstract function

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#12]
**Describe the bug**
When opening any manga link it shows the error seen in screenshot

**To Reproduce**
1. Go to https://mangadex.org/title/5/naruto or any manga link
2. See error

**Expected behavior (optional)**
Not show any error

**Screenshots**
![error](https://user-images.githubusercontent.com/76645315/103169078-ce49c980-485e-11eb-92f5-d8e9c04a4631.png)

**Browser**
Chrome (0.1.5)

**Options and logs**
```
Logs :
Title.link is an abstract function

Debug:
{"lastSync":1609059050297,"logs":[{"d":1609065170425,"msg":"Title.link is an abstract function"},{"d":1609065192940,"msg":"Title.link is an abstract function"},{"d":1609065272681,"msg":"Title.link is an abstract function"},{"d":1609065389391,"msg":"Title.link is an abstract function"},{"d":1609065396077,"msg":"Title.link is an abstract function"},{"d":1609065402786,"msg":"Title.link is an abstract function"},{"d":1609065448592,"msg":"Title.link is an abstract function"},{"d":1609065478209,"msg":"Title.link is an abstract function"},{"d":1609065590256,"msg":"Title.link is an abstract function"},{"d":1609065623073,"msg":"Title.link is an abstract function"},{"d":1609065632013,"msg":"Title.link is an abstract function"},{"d":1609065639280,"msg":"Title.link is an abstract function"},
```

**Additional context**
I have used import all function and export to mangaupdates before [ main Service is MAL] but not sure if this is relevant

**Comment by Pancakes0** [comment]
ohh yeah i didnt notice that cause i was still reading, i tried on some other mangas: 
Skeleton Soldier Couldn't Protect the Dungeon (current read) - error/works
Againts the god - works
Build up - works 
Yoru to Futari - works 
The Gods Comes and Go - error 
Eleceed - error 
Tokugawa no Saru - works 
 i dunno sometimes it works sometimes it doesnt?

**Comment by Pancakes0** [comment]
scratch that, i think its fixed? i refreshed all of the error ones and also naruto but it works. i also opened half of the latest update page mangas

**Comment by Glagan** [comment]
Might be related to #4, I'll look what's wrong.

**Comment by Zw012d** [comment]
I have noticed that error is because of AnimePlanet Services, the error goes away if i disabled it. Also i was unable to Export SyncDex to AnimePlanet as it hangs as seen below
![bug](https://user-images.githubusercontent.com/76645315/103174032-d157b080-4884-11eb-8ab9-5f3654f9cc6a.png)

**Comment by Glagan** [comment]
The Export issue was not related to this but there was an error, it's fixed, I'll publish a new version soon and when it updates to ``0.1.6`` you can activate **Anime Planet** again.
