### ISSUE TITLE
[BUG] Refreshing Dropbox token (expired)

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#13]
**Describe the bug**
SyncDex not syncing to Dropbox

**To Reproduce**
1. Go to Save Sync tab 
2. Click on Export
3. See error

**Expected behavior (optional)**
Sync to Dropbox

**Screenshots**

**Browser**
Chrome (0.1.6)

**Options and logs**
```
{"import":1609138581350,"lastSync":1609103080000,"logs":[{"d":1609138984496,"msg":"Refreshing Dropbox token (expired 1609103088797)"}],"options":{"acceptLowScore":false,"autoSync":true,"biggerHistory":true,"chapterStatus":false,"chaptersSaved":400,"checkOnStartup":true,"checkOnStartupCooldown":30,"checkOnStartupMainOnly":true,"colors":{"higherChapter":"transparent","highlights":["rgba(82, 190, 90, 0.6)","rgba(107, 177, 95, 0.6)","rgba(55, 168, 61, 0.6)"],"lowerChapter":"rgba(180, 102, 75, 0.5)","nextChapter":"rgba(104, 115, 251, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"confirmChapter":true,"errorNotifications":true,"favoriteLanguage":"all","groupTitlesInLists":true,"hideHigher":true,"hideLast":false,"hideLower":true,"highlight":true,"iconsSilentAfterSync":false,"linkToServices":true,"mainService":"mal","mdUpdateSyncDex":true,"noReloadStatus":true,"notifications":true,"originalThumbnail":false,"overviewMainOnly":true,"progressInThumbnail":true,"saveOnlyHigher":true,"saveOnlyNext":false,"saveOpenedChapters":true,"separateLanguages":true,"services":["mal","mu","al","ku","ap"],"subVersion":6,"thumbnail":true,"thumbnailMaxHeight":80,"tokens":{"anilistToken":"set","kitsuToken":"set","kitsuUser":"set"},"updateMD":true,"updateOnlyInList":false,"useMochi":true,"version":0.1},"saveSync":{"expires":1609103088797,"service":"Dropbox","token":"set","refresh":"missing"}}
```

**Additional context**
I have checked the file in Dropbox its not updating

**Comment by Zw012d** [comment]
I have tried Logging in and out a few times and it works now

**Comment by Glagan** [comment]
It's weird that you only see the first message in your logs, but this should have been fixed already in 0ba9f53, but it's not out yet I did it too late and will be in ``0.1.7``.

It will works if you logout and login again, but you have to manually do it, if you keep logged in too long your token will expire and that's when the error happen.

**Comment by Zw012d** [comment]
>  It will works if you logout and login again, but you have to manually do it, if you keep logged in too long your token will expire and that's when the error happen.
I see that makes sense, will be waiting for 0.1.7 .  Also I have some queries regarding History as it delete some of the manga in the history after some time but i can't see history in the logs/debug so not sure how to create a bug report. Will check if it happens again

**Comment by Zw012d** [comment]
> It will works if you logout and login again, but you have to manually do it, if you keep logged in too long your token will expire and that's when the error happen.

I see that makes sense, will be waiting for 0.1.7 . Also I have some queries regarding History as it delete some of the manga in the history after some time but i can't see history in the logs/debug so not sure how to create a bug report. Will check if it happens again
