### ISSUE TITLE
[BUG] Manga History gets removed from SyncDex

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#14]
**Describe the bug**
Last Visit and Last Read get resetted to None and Started Date of manga resetted to 1 Jan 2020 (12 Jan 2020 in some cases) after some time if the Manga is synced with MAL. If no MAL id then there is no issue.

**To Reproduce**
1. Go to any Manga with MAL id
2. Set Started date or read the manga to Set Last Visit/Read Date [checked that Start Date is changed in MAL] 
3. Wait after some time like 1 hr (i generally close the browser if not using it)
4. Check the Manga Link again or its MAL link

**Expected behavior (optional)**
Last Visit, Last Read and Started Date should not get changed or resetted

**Screenshots**
![Untitled1](https://user-images.githubusercontent.com/76645315/103228403-c40af680-4956-11eb-8e9c-27828da1fe3f.png)

**Browser**
Chrome (0.1.6)

**Options and logs**
```
Nothing is logs regarding history
```

**Additional context**
I thought that it was an issue with using SyncDex with MAL-Sync but not sure if this is the case based on my discussion with them
https://discord.com/channels/358599430502481920/358599430502481921/793127113707749396

**Comment by Glagan** [comment]
If I understand correctly, you mean the **Last read** and **Last visit** date displayed in the **History** page ?  
Those dates are only used in **SyncDex** and are just used for you to check what you did.

The **Started Date** on the other end should not be changed if you did not change it.  
Can you please still put your logs since they also have your options so I can check.  

If you want to try you can disable **Auto Sync** under the **Title Page** category so it won't automatically sync and you can see if it changed on **MyAnimeList**.

There might be an error when parsing the date but I think it would have been noticed before.

**Comment by Pancakes0** [comment]
i didnt notice any bugs as such. i read kingdom yesterday (start date 9 jan 2019) and still hasnt changed. though ive experienced 2-3 mangas being forgotten completely but i dont mind, other than that i dont see anything wrong yet.

**Comment by Glagan** [comment]
The month and day where actually reverted in **Import** (not in a *regular* single get like while reading or in the Title page), and if the "reverted" date was lower than the real date it would replace it.  
Sorry about that, weird that it got through, I checked everything 10 times since every site has it's own date format and MyAnimeList even use 2 different.

I guess you had the **Check Lists on Startup** option enabled since you mentionned closing your browser, so when you opened it again it would import and set the wrong date.  

It's fixed in ``0.1.7``.  
Maybe you should Import from MyAnimeList after the ``0.1.7`` update to fix the dates in your save and avoid erasing your real date.

**Comment by Zw012d** [comment]
>It's fixed in 0.1.7.
Maybe you should Import from MyAnimeList after the 0.1.7 update to fix the dates in your save and avoid erasing your real date.

Started/Completed is not reverting after 0.1.7 update will check for few days to be sure

> The month and day where actually reverted in Import (not in a regular single get like while reading or in the Title page), and if the "reverted" date was lower than the real date it would replace it.

I also didn't noticed it earlier that dates were changed, only found out when the mangas were disappearing from the history page.

> Sorry about that, weird that it got through, I checked everything 10 times since every site has it's own date format and MyAnimeList even use 2 different.

No problem it is still in beta and someday it might replace MMD as it has lot more features

> I guess you had the Check Lists on Startup option enabled since you mentionned closing your browser, so when you opened it again it would import and set the wrong date.

Yes these are my settings should have shared it earlier also i have disabled Mal-Sync Autotracking for Mangadex [ Mal-Sync background sync is enabled as it can only be turned off for both Anime and Manga at the same time]
Logs
`{"import":1609227120555,"lastSync":1609227439000,"logs":[{"d":1609221088794,"msg":"Save already synced with Dropbox"},{"d":1609221088813,"msg":"Importing lists"},{"d":1609221088816,"msg":"Importing MyAnimeList"},{"d":1609221109083,"msg":"Imported MyAnimeList in 20267ms"},{"d":1609221109088,"msg":"Done Importing lists"},{"d":1609221140807,"msg":"No external lastSync or forced, uploading save."},{"d":1609221145005,"msg":"Uploaded Local Save to Dropbox"},{"d":1609221145012,"msg":"Synced your save with Dropbox"},{"d":1609223784962,"msg":"Save already synced with Dropbox"},{"d":1609223784966,"msg":"Importing lists"},{"d":1609223784967,"msg":"Importing MyAnimeList"},{"d":1609223807155,"msg":"Imported MyAnimeList in 22188ms"},{"d":1609223807160,"msg":"Done Importing lists"},{"d":1609223885367,"msg":"Error on request [https://myanimelist.net/ownlist/manga/116778/edit?hideLayout]: TypeError: Failed to fetch>> TypeError: Failed to fetch"},{"d":1609223904519,"msg":"No external lastSync or forced, uploading save."},{"d":1609223912034,"msg":"Uploaded Local Save to Dropbox"},{"d":1609223912036,"msg":"Synced your save with Dropbox"},{"d":1609223965199,"msg":"No external lastSync or forced, uploading save."},{"d":1609223971515,"msg":"Uploaded Local Save to Dropbox"},{"d":1609223971517,"msg":"Synced your save with Dropbox"},{"d":1609224024612,"msg":"No external lastSync or forced, uploading save."},{"d":1609224026984,"msg":"Uploaded Local Save to Dropbox"},{"d":1609224026988,"msg":"Synced your save with Dropbox"},{"d":1609224097181,"msg":"No external lastSync or forced, uploading save."},{"d":1609224099584,"msg":"Uploaded Local Save to Dropbox"},{"d":1609224099587,"msg":"Synced your save with Dropbox"},{"d":1609224217415,"msg":"No external lastSync or forced, uploading save."},{"d":1609224220312,"msg":"Uploaded Local Save to Dropbox"},{"d":1609224220322,"msg":"Synced your save with Dropbox"},{"d":1609224366005,"msg":"No external lastSync or forced, uploading save."},{"d":1609224368579,"msg":"Uploaded Local Save to Dropbox"},{"d":1609224368583,"msg":"Synced your save with Dropbox"},{"d":1609224400561,"msg":"Save already synced with Dropbox"},{"d":1609224400566,"msg":"Startup script executed less than 30minutes ago, skipping"},{"d":1609227083206,"msg":"Save already synced with Dropbox"},{"d":1609227083212,"msg":"Importing lists"},{"d":1609227083213,"msg":"Importing MyAnimeList"},{"d":1609227120552,"msg":"Imported MyAnimeList in 37339ms"},{"d":1609227120557,"msg":"Done Importing lists"},{"d":1609227205781,"msg":"No external lastSync or forced, uploading save."},{"d":1609227209734,"msg":"Uploaded Local Save to Dropbox"},{"d":1609227209737,"msg":"Synced your save with Dropbox"},{"d":1609227275539,"msg":"No external lastSync or forced, uploading save."},{"d":1609227280127,"msg":"Uploaded Local Save to Dropbox"},{"d":1609227280129,"msg":"Synced your save with Dropbox"},{"d":1609227333665,"msg":"No external lastSync or forced, uploading save."},{"d":1609227336015,"msg":"Uploaded Local Save to Dropbox"},{"d":1609227336026,"msg":"Synced your save with Dropbox"},{"d":1609227398878,"msg":"Save already synced with Dropbox"},{"d":1609227398883,"msg":"Startup script executed less than 30minutes ago, skipping"},{"d":1609227435982,"msg":"No external lastSync or forced, uploading save."},{"d":1609227439570,"msg":"Uploaded Local Save to Dropbox"},{"d":1609227439573,"msg":"Synced your save with Dropbox"}],"options":{"acceptLowScore":false,"autoSync":true,"biggerHistory":true,"chapterStatus":true,"chaptersSaved":400,"checkOnStartup":true,"checkOnStartupCooldown":30,"checkOnStartupMainOnly":true,"colors":{"higherChapter":"transparent","highlights":["rgba(82, 190, 90, 0.6)","rgba(107, 177, 95, 0.6)","rgba(55, 168, 61, 0.6)"],"lowerChapter":"rgba(180, 102, 75, 0.5)","nextChapter":"rgba(104, 115, 251, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"confirmChapter":false,"errorNotifications":true,"favoriteLanguage":"all","groupTitlesInLists":true,"hideHigher":true,"hideLast":false,"hideLower":true,"highlight":true,"iconsSilentAfterSync":true,"linkToServices":true,"mainService":"mal","mdUpdateSyncDex":true,"noReloadStatus":true,"notifications":true,"originalThumbnail":false,"overviewMainOnly":true,"progressInThumbnail":true,"saveOnlyHigher":true,"saveOnlyNext":false,"saveOpenedChapters":true,"separateLanguages":true,"services":["mal","mu","al","ku","ap"],"subVersion":7,"thumbnail":true,"thumbnailMaxHeight":80,"tokens":{"anilistToken":"set","kitsuToken":"set","kitsuUser":"set"},"updateMD":true,"updateOnlyInList":false,"useMochi":true,"version":0.1},"saveSync":{"expires":1609234882791,"service":"Dropbox","token":"set","refresh":"missing"}}`

>If I understand correctly, you mean the Last read and Last visit date displayed in the History page ?

Yes 

>Those dates are only used in SyncDex and are just used for you to check what you did.

But it should not get changed if we don't change anything but close browser and open it after sometime 
Before
![Screenshot3](https://user-images.githubusercontent.com/76645315/103268893-6c15d380-49da-11eb-9feb-8cb5de1ac501.png)

After 
![Screenshot4](https://user-images.githubusercontent.com/76645315/103268896-6d470080-49da-11eb-9988-ff01ca78ed94.png)
as long as it has Mal id Last read and Last visit date will get removed which should not happen imho

**Comment by Glagan** [comment]
Fixed in ``0.1.8``, all fields should now not be deleted after an import.

**Comment by Zw012d** [comment]
Thanks it is fixed now

**Comment by Zw012d** [comment]
Some Titles are getting removed from history but unable to see pattern which and when manga gets removed from history. Yesterday there were 20 mangas in history now today only 10. Will find more info and update this thread accordingly

Chrome (0.1.9)
Debug:
```
{"import":1609683707296,"lastSync":1609684407000,"logs":[],"options":{"acceptLowScore":false,"autoSync":true,"biggerHistory":true,"chapterStatus":true,"chaptersSaved":400,"checkOnStartup":true,"checkOnStartupCooldown":30,"checkOnStartupMainOnly":true,"colors":{"higherChapter":"transparent","highlights":["rgba(82, 190, 90, 0.6)","rgba(107, 177, 95, 0.6)","rgba(55, 168, 61, 0.6)"],"lowerChapter":"rgba(180, 102, 75, 0.5)","nextChapter":"rgba(104, 115, 251, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"confirmChapter":false,"errorNotifications":true,"favoriteLanguage":"all","groupTitlesInLists":true,"hideHigher":true,"hideLast":false,"hideLower":true,"highlight":true,"iconsSilentAfterSync":true,"linkToServices":true,"mainService":"mal","mdUpdateSyncDex":true,"noReloadStatus":true,"notifications":true,"originalThumbnail":false,"overviewMainOnly":true,"progressInThumbnail":true,"saveOnlyHigher":true,"saveOnlyNext":false,"saveOpenedChapters":true,"separateLanguages":true,"services":["mal","mu","al","ku","ap"],"silentUpdate":false,"subVersion":9,"thumbnail":true,"thumbnailMaxHeight":80,"tokens":{"anilistToken":"set","kitsuToken":"set","kitsuUser":"set"},"updateMD":true,"updateOnlyInList":false,"useMochi":true,"version":0.1},"saveSync":{"expires":1609687998178,"refresh":"set","service":"Dropbox","token":"set"}}
```

**Comment by Zw012d** [comment]
I have disabled this option and as far as i can tell history bug issue doesn't occur.
![Screenshot](https://user-images.githubusercontent.com/76645315/106091655-e27d3100-6152-11eb-9974-78f28d0457e9.png)

Steps:
1) Enable this option
2) Wait some time and reopen browser
3) Check History [not removed at this stage]
4) Open and read new manga
5) Only last 9 or so manga remain in History when checking again

**Comment by Glagan** [comment]
Sorry about the delay on this.

So everything works fine with the ``Check Lists on Startup`` disabled, and then if you open a new manga (is reading mandatory ?) the History gets updated ?  

I'll try to reproduce, in the meantime, if you're not reading outside of your browser (or any browser synced with Dropbox or Google Drive), you don't need the ``Check Lists on Startup`` option.  
I made this option for Tachiyomi readers, where the list is synced directly on MyAnimeList for example, and it's just easier to import it on startup rather than trying to do clever checks in some places to keep up to date.

**Comment by Zw012d** [comment]
Please ignore the earlier comment. What happened was if we manually update using `Set Latest` Dialog box (reading manga on other apps) most of the manga history disappears. I mistake it for `Check Lists on Startup` as i didn't manually update after disabling the option so it was working fine.

Steps:
1) Make sure that History list is not small [preferably more than 30]
2) Refresh history page
3) Change any of the manga last read by selecting `Set Latest` dialog box
4) Refresh history page and manga history disappears.

Also i want to ask what is the max limit of history in Syncdex if there is such a limit and is it possible to filter the History list based on Higher chapters are available / Latest chapter read

**Comment by Glagan** [comment]
There is currently no limit to the History, it should never be deleted, It's an error on my end where I don't correctly get or save it.

**Comment by Glagan** [comment]
I was not initializing the History in all other pages than reading, it should be good now with the next version (``0.2.8``).

**Comment by Zw012d** [comment]
> I was not initializing the History in all other pages than reading, it should be good now with the next version (`0.2.8`).

Thanks, closing this issue as it seems to be fixed
