### ISSUE TITLE
duplicating sync/edit [BUG]

### ISSUE THREAD

**Issue by Pancakes0** [Glagan/SyncDex#15]
**Describe the bug**
it was just one in chapter 1 then duplicated to 3 in chapter 8 (do know that when you click next chapter page doesnt refresh and yes it does go away with a refresh) (also that it shows 2 notification of (Not Updated) and 1 updated one. which i think it means that the sync logo was of the past chapter. it was updating but the past chapter wasnt umm... deleted? or idk whats the word.) (or maybe it dint refresh the past one and added a new one from the new chapter?)

**To Reproduce**
1. Go to read/open a manga 
2. Click on keep reading or clicking next chapter till it happens 
3. Scroll down to 

**Expected behavior (optional)**
expected for only one to show up every chapter 

**Screenshots**
![Screen Shot 2020-12-29 at 10 01 32 AM](https://user-images.githubusercontent.com/73923883/103253908-159a9c00-49be-11eb-8df2-e443d7bed00b.png)
![Screen Shot 2020-12-29 at 10 20 42 AM](https://user-images.githubusercontent.com/73923883/103254252-8d1cfb00-49bf-11eb-91f5-8f33148c4111.png)( i went back to prev chap to ss)

**Browser**
Firefox 1.7 (i havent refreshed the page after installing 1.7 to see of it keeps duplicating)
**Options and logs**
none? the last log was update and this duplicated 3rd time after and i dont see it here so i dont know but here(i also did some re-importing) k thanks
Click the **Debug** button on the navigation menu on the left in the Options and copy paste it's content here.
```  
{"logs":[{"d":1608988859655,"msg":"Installation version 0.1.4"},{"d":1608988899392,"msg":"Importing lists"},{"d":1608988899394,"msg":"Importing MyAnimeList"},{"d":1608988913395,"msg":"Imported MyAnimeList in 14001ms"},{"d":1608988913404,"msg":"Done Importing lists"},{"d":1609038638166,"msg":"Updating from version 0.1.4 to 0.1.5"},{"d":1609072060367,"msg":"Error on request [https://mochi.nikurasu.org/connections/MangaDex/47780]: AbortError: The operation was aborted. "},{"d":1609072060555,"msg":"Mochi error: code 0 body {}"},{"d":1609137071418,"msg":"Updating from version 0.1.5 to 0.1.6"},{"d":1609206877147,"msg":"Updating from version 0.1.6 to 0.1.7"}],"options":{"hideHigher":false,"hideLower":true,"hideLast":false,"highlight":true,"groupTitlesInLists":true,"thumbnail":true,"originalThumbnail":false,"progressInThumbnail":true,"thumbnailMaxHeight":80,"separateLanguages":true,"favoriteLanguage":"all","saveOpenedChapters":true,"chaptersSaved":100,"saveOnlyHigher":true,"saveOnlyNext":false,"confirmChapter":true,"updateOnlyInList":false,"iconsSilentAfterSync":true,"linkToServices":true,"overviewMainOnly":true,"autoSync":true,"mdUpdateSyncDex":false,"biggerHistory":false,"chapterStatus":false,"notifications":true,"errorNotifications":true,"useMochi":true,"acceptLowScore":false,"updateMD":false,"checkOnStartup":false,"checkOnStartupMainOnly":true,"checkOnStartupCooldown":30,"services":["mal","al"],"mainService":"mal","noReloadStatus":true,"tokens":{"anilistToken":"set"},"colors":{"highlights":["rgba(28, 135, 141, 0.8)","rgba(22, 65, 87, 0.8)","rgba(28, 103, 141, 0.8)"],"nextChapter":"rgba(199, 146, 2, 0.4)","higherChapter":"transparent","lowerChapter":"rgba(180, 102, 75, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"version":0.1,"subVersion":7}}

**Additional context**

**Comment by Pancakes0** [comment]
also i dont know if it a bug but its like this. lets say i opened a manga/refresh the page then change tabs before fully loading then i sleep the laptop/close then when i open that tab which i refresh the notification doesnt disappear and the x button also doesnt work so youd need to restart again

https://user-images.githubusercontent.com/73923883/103281753-ae590800-4a0e-11eb-98b1-b3ee1edeec8b.mov

![Screen Shot 2020-12-29 at 7 43 19 PM](https://user-images.githubusercontent.com/73923883/103281766-b44ee900-4a0e-11eb-80fa-7f49628ff712.png)
(close also doesnt work)
edit: this was also in mmd just asking if its a bug or not thanks

**Comment by Glagan** [comment]
Having duplicate overview (also in Title page) is *expected* when **SyncDex** is updated, since Firefox reload the scripts even if it already loaded on a page.

But the duplicate overview when reading is a bug, I'll look at it.

For the second error, it's really specific and is just be related to **SimpleNotification** ([Glagan/SimpleNotification](https://github.com/Glagan/SimpleNotification)) and the way notification are created, if you also had this problem in MyMangaDex.  
I'll try to look at it, but I don't know if it will be for the next version.

**Comment by Pancakes0** [comment]
yeah thanks. dont worry about i dont mind it since a refresh can fix it just thought you should know! 🥳

**Comment by Glagan** [comment]
I couldn't reproduce the duplicate overview, even when changing chapters fast, so I don't know how you managed to do it, but I fixed a possible bug when there was a chapter change, and I added a notification when **SyncDex** is reloaded (displayed when  there is an update if you have a tab open).

**Comment by Pancakes0** [comment]
i think its because i keep my tabs open and rarely shuts my laptop down then use it again? dunno. but thank you~
