### ISSUE TITLE
[BUG] Unable to use Save Viewer Search Function

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#18]
**Describe the bug**
No results when searching for manga in Save Viewer Search Function by Mangadex Id/Name

**To Reproduce**
1. Go to Save Viewer
2. Search Any Manga by Name or id
3. See error "Nothing found in your Save !"

**Expected behavior (optional)**
Should be able to Search Manga by Mangadex Id and Manga title

**Screenshots**
Like for Naruto Manga [https://mangadex.org/title/5/naruto]
![Screenshot 2020-12-31 032933](https://user-images.githubusercontent.com/76645315/103383448-c2892c00-4b18-11eb-9b5a-3b67f74939a0.png)
![Screenshot 2020-12-31 033835](https://user-images.githubusercontent.com/76645315/103383693-b2be1780-4b19-11eb-9ee3-c342b013c576.png)

**Browser**
Chrome (0.1.8)

**Additional context**
If possible search manga titles like "Tensei Shitara Slime Datta Ken" by just using words like "Slime" etc but not sure if this is possible due to non alphanumeric tiles like below, in that case just be able to search by mangadex id only
![Screenshot 2020-12-31 040031](https://user-images.githubusercontent.com/76645315/103384531-c323c180-4b1c-11eb-8918-90713d1b066b.png)

**Comment by Glagan** [comment]
Oops, typo, fixed it last time and must have deleted a word without checking right after...

Search "inside" names already works, and with special chars :)

**Comment by Zw012d** [comment]
> Oops, typo, fixed it last time and must have deleted a word without checking right after...
Search "inside" names already works, and with special chars :)

Thanks will be waiting for the fix patiently :)

**Comment by Glagan** [comment]
Fixed in ``0.1.9``, you can also now search by **MangaDex** ID which was missing previously (Only Services IDs were used).
