### ISSUE TITLE
[BUG] Chapter not updated if no service

### ISSUE THREAD

**Issue by cpiber** [Glagan/SyncDex#20]
**Describe the bug**
Updating does not work if no service is found.

**To Reproduce**
1. Take a new manga like https://mangadex.org/title/58870/my-butler-not-lover
2. Open chapter

**Expected behavior (optional)**
Simply update the internal database

**Screenshots**
![image](https://user-images.githubusercontent.com/59023762/103412097-df068200-4b73-11eb-8b14-607446552bf8.png)
![image](https://user-images.githubusercontent.com/59023762/103412122-f180bb80-4b73-11eb-96de-3fecd79b1ff1.png)

**Browser**
Firefox 84.0 

**Additional context**
A notification "No chapter found" (would be more appropriate "No service found") is shown, as well as an update with no service listed. No update is actually performed.

**Comment by Glagan** [comment]
This is not related to services, this chapter does not have a "valid" chapter value, it's an empty string, **SyncDex** can't find it and it need to be fixed in MangaDex.  
But, it's in the chapter name so I will add a fallback to find the progress in the chapter name.

**Comment by cpiber** [comment]
Oh, you're right, I didn't notice that
