### ISSUE TITLE
[REQUEST] Mangadex Api v2 Support

### ISSUE THREAD

**Issue by Zw012d** [Glagan/SyncDex#25]
link - https://mangadex.org/thread/351011
> Changelog
2020-01-11
>- Added read to the chapter entities in /user/:id/followed-updates. These are based on the actual stored markers, so under certain conditions they may be false even though chapters may appear as read on the website, such as when a manga is followed as Completed.
>- [Future breaking] Added title the simple manga entities in /user/:id/followed-updates. IMPORTANT: This is because the entity erroneously used the name field for the title. Both fields currently have identical information, and name will be removed by the end of the month in a breaking change.
>- Fixed the baseUrl in the index to reflect the new url.

I think there might be some issues with the SyncDex due to api changes like i am not seeing the Services icon as seen in the screenshot.
![Screenshot 2021-01-11 111738](https://user-images.githubusercontent.com/76645315/104150149-ef81ec80-53fe-11eb-9f8d-11b3be53a7c0.png)

**Comment by Glagan** [comment]
Well, they changed everything without warning (or I didn't see it ?).

I'm updating for the latest API version and I'll update it as soon as it's ready.

**Comment by Glagan** [comment]
I should have fixed everything, until they change it again...  
Will be up with version ``0.2.0``.

**Comment by Zw012d** [comment]
>I should have fixed everything, until they change it again...

well according to their statement below it might change in MangaDex v5 :)

> Now, this API is not complete and most likely won't ever entirely be. We wrote it as somewhat of a stopgap measure to both improve usability for 3rd parties as well as to create a solid base for us to work on a couple of features for the current site while we're doing the entire site rework, known as MangaDex v5. Future endpoints should include at least one for the latest updates (i.e. the frontpage chapter listing) among other , but if you have requests or improvement suggestions, let us know. By the way, you should expect the API to change again for v5 so sorry about that, but this version at least resembles the approach we're taking with that one.

> Will be up with version 0.2.0.

thanks i will test for few days and update this thread accordingly

**Comment by vessalioz** [comment]
The site staff mentioned some changes to the API on the official discord [server](https://discord.gg/mangadex)

**Comment by Glagan** [comment]
They mentionned API changes Yesterday, when they changed it, I'm on the server and I follow at least the #announcements channel and I did not see anything about a breaking change.  
The changes that broke the addon aren't documented, since I'm not really using the API when you're reading but the custom events they expose in the reader, and they changed those to follow their API. They don't expect people to use these, and it's only for their purpose so it's normal.

**Comment by Zw012d** [comment]
Closing this issue as no major changes has been seen in v2 api to break syncdex for a while now.

> Changelog of Manganese API v2

>2021-01-17
>- Fixed group leaders and members still not being able to read their delayed chapters

>2021-01-15
>- Fixed group leaders and members not having permission to read their own delayed chapters.
>- Added parameter blockgroups to all endpoints that return a list of chapters (e.g. /manga/:id/chapters and others).
>- Added parameters type and hentai to /user/:id/followed-manga (same params that followed-updates already had).
>- Added mainCover to /user/:id/followed-manga and /user/:id/manga/:id.

**Comment by Zw012d** [comment]
Closing this issue as no major changes has been seen in v2 api to break syncdex for a while now.

> Changelog of Mangadex API v2

>2021-01-17
>- Fixed group leaders and members still not being able to read their delayed chapters

>2021-01-15
>- Fixed group leaders and members not having permission to read their own delayed chapters.
>- Added parameter blockgroups to all endpoints that return a list of chapters (e.g. /manga/:id/chapters and others).
>- Added parameters type and hentai to /user/:id/followed-manga (same params that followed-updates already had).
>-Added mainCover to /user/:id/followed-manga and /user/:id/manga/:id.
