### ISSUE TITLE
[BUG] 0.2.0 breaks "full size original cover" 0.1.9 works

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#29]
**Describe the bug**
in V0.2.0 the full size cover option under "Display cover in lists" does not produce the full size image, v0.1.9 does.

**To Reproduce**
1. install v.0.2.0
2. activate full size covers
3. hover a manga name or chapter title on the list page
4. it does not show the full size image

**Expected behavior (optional)**
the full size cover should be displayed

**Screenshots**
https://user-images.githubusercontent.com/49324581/104232319-790dda80-5450-11eb-9e68-8fbc38ec4b06.mp4
![](https://user-images.githubusercontent.com/49324581/104232319-790dda80-5450-11eb-9e68-8fbc38ec4b06.mp4)

**Browser**
Firefox 86.0a1 (2021-01-11) (64-bit)

**Options and logs**
did it on a fresh firefox profile with only the full size option checked in.

downgrading to 0.1.9 works with no issue.

**Comment by Glagan** [comment]
Oops, messed up the URLs while refactoring the links related to MangaDex, will be fixed in the next version.

**Comment by Glagan** [comment]
Should be fixed with version ``0.2.1``, sorry for the wait.
