### ISSUE TITLE
[QUESTION] What does the SyncDex reloaded notification mean ?

### ISSUE THREAD

**Issue by Pancakes0** [Glagan/SyncDex#30]
![Screen Shot 2021-01-12 at 9 18 05 PM](https://user-images.githubusercontent.com/73923883/104319370-b9865a80-551b-11eb-90aa-46afb633a1d9.png)
what does this mean? 
Thanks, and also thank you for your hard work and all 🧁
have a good day

**Comment by cpiber** [comment]
It means that the extension updated and that you should reload the tab to avoid duplicate widgets.

**Comment by Glagan** [comment]
Yes it's just a notification with a quick reload button when SyncDex is already loaded on the page and it was updated.  
Firefox reload all scripts when an addon is updated, and to avoid having multiple overview, or checking for chapter change multiple times when you read I just do nothing and tell you to reload.

**Comment by Pancakes0** [comment]
thanks~
