### ISSUE TITLE
[BUG] unable to unfollow a manga on mangadex

### ISSUE THREAD

**Issue by M0UL** [Glagan/SyncDex#35]
i cannot unfollow a manga on mangadex. if i try to unfollow a manga.  than refresh the page the manga is still listed as being followed. if turn of the extension it works fine.

**Comment by Glagan** [comment]
Please follow the issue template.

Sorry, forgot a parameter in the API call

**Comment by Glagan** [comment]
Sorry about the delay, it's fixed in ``0.2.4``.
