### ISSUE TITLE
[BUG] Volume Reset miscount

### ISSUE THREAD

**Issue by cpiber** [Glagan/SyncDex#40]
**Describe the bug**
Title https://mangadex.org/title/36400/wendy-the-florist miscounts on volume reset (off-by-one). Haven't checked other titles.
Same happens with a fresh install of SyncDex.
There are no extra chapters or ones in other languages.

**Screenshots**
After "Set Latest":
![image](https://user-images.githubusercontent.com/59023762/106353936-60297400-62ee-11eb-970a-c38d9f92f8a1.png)

Without SyncDex:
![image](https://user-images.githubusercontent.com/59023762/106353952-818a6000-62ee-11eb-9601-5c178fc57851.png)

**Comment by Glagan** [comment]
I was not handling when the first chapter of a volume was not 0, fixed in the next version (``0.2.9``).

**Comment by Pancakes0** [comment]
saame...

**Comment by Glagan** [comment]
Are you on the latest version (currently ``0.2.11``) ? This should have been fixed since ``0.2.9``.  
Could I have a link to the Title where this still happens.

Edit: Nevermind, it's still bugged sometimes if you have some languages active, looks like it's still missing something, I'll look at it.

**Comment by Glagan** [comment]
Sorry about the delay on this, should be fixed with the next version (``0.2.12``).
