### ISSUE TITLE
[Request] Mangadex links to external sites don't update chapters read

### ISSUE THREAD

**Issue by counttec** [Glagan/SyncDex#43]
For popular manga where there is a direct link to the official translation (i.e. MHA), opening the chapter in Mangadex does not cause Syncdex to update records. See below for the standard look of the chapter.
![image](https://user-images.githubusercontent.com/7998434/107995052-2c5f7700-6f9b-11eb-8234-55f75679a86f.png)

**Comment by Glagan** [comment]
Hi ! Sorry for the really long delay !

The delayed and external detection was broken since the new ``saveOnLastPage`` option, sorry about that !  
It will be fixed in the next version (``0.2.13``).
