### ISSUE TITLE
[BUG] "set latest" when title is set to anything other than "reading", changes the status to "reading".

### ISSUE THREAD

**Issue by Jerrk** [Glagan/SyncDex#44]
**Describe the bug**
clicking "set latest" in the chapter list on a title page always changes the status to reading. doesnt matter if its "dropped" "re-reading" "complete", it will always change to "reading"

**To Reproduce**
go to any title page
add to any list other than reading
"set latest" on any chapter
list is now changed to reading.

**Expected behavior (optional)**
it should donly update the tracking to that specific chapter, not change the list.

**Browser**
Firefox 87.0a1 (2021-02-16) (64-bit)

**Options and logs**
can't paste because it is filled with dropbox spam, if need be ill give you the .txt but this doesnt seem like such a specific issue, although who knows.

**Comment by Glagan** [comment]
Sorry about the delay on that !

It should be fixed in the next version (``0.2.13``).
