### ISSUE TITLE
[BUG] Volume in Reading Progress don't change if Set Latest is below the current volume no.

### ISSUE THREAD

**Issue by arbuilder** [Glagan/SyncDex#45]
For Ex. 
https://mangadex.org/title/20523/beastars

if u _set latest_ 193 chapter volume 22 then volume no. get changed correctly in both syncdex and mangadex

![Screenshot 2021-02-24 133926](https://user-images.githubusercontent.com/78140816/108967670-d038d900-76a5-11eb-9e02-a1ff05973f51.png)

then if u _set latest_ 134 chapter volume 16 then volume no. doesn't get changed in both syncdex and mangadex and stays at 22
![Screenshot 2021-02-24 133948](https://user-images.githubusercontent.com/78140816/108967663-cf07ac00-76a5-11eb-8c3a-ee1154041a49.png)

**Comment by Glagan** [comment]
I was checking the volume and assigning only the highest one, I'm not sure exactly why but it's fixed in the next version (``0.2.14``).
