### ISSUE TITLE
[BUG] Lower chapters still showing although "Hide Lower Chapters" is checked.

### ISSUE THREAD

**Issue by lol480phuh** [Glagan/SyncDex#7]
As the title states, lower chapters for the series in the "Follows" list are still showing despite the fact that the option to hide them is checked. 
Same with last read chapters.

see Screenshot below

![image](https://user-images.githubusercontent.com/52804334/103151783-725d4300-4781-11eb-96f1-cb6b03a5f5b5.png)

**Comment by lol480phuh** [comment]
Never mind, It updated when I read the latest chapter of the Mangas in question. Sorry for opening an issue, lol.

**Comment by lol480phuh** [comment]
Even after reading the chapters, nothing updated.

See screenshot below:

![image](https://user-images.githubusercontent.com/52804334/103152013-ca954480-4783-11eb-97e1-ae3e9e9e7c23.png)

![image](https://user-images.githubusercontent.com/52804334/103152015-da148d80-4783-11eb-96df-c4e28b94ad50.png)

![image](https://user-images.githubusercontent.com/52804334/103152022-f1537b00-4783-11eb-9384-25d9facd0cbc.png)

**Comment by Glagan** [comment]
Is **Komi-san** in your list, when you go on it's title page, is there a summary with your progress in it ?  
Also, did you read these chapters in your browser or did you just click the eye button ?

Can you post your logs, you can copy/paste them with the "Debug" button on the left in the options.

**Comment by lol480phuh** [comment]
Yes it is on my list (see screenshot) with progress on booth SyncDex and MAL

![image](https://user-images.githubusercontent.com/52804334/103152229-4b554000-4786-11eb-9db2-f93ecfcf1179.png)

I read the chapters in the browse and checked after that but nothing changed it only highlighted the "read" button and nothing more.

**Here're the logs:**

`{"logs":[{"d":1608983483393,"msg":"Installation version 0.1.4"}],"options":{"acceptLowScore":false,"autoSync":true,"biggerHistory":true,"chapterStatus":true,"chaptersSaved":400,"checkOnStartup":false,"checkOnStartupCooldown":30,"checkOnStartupMainOnly":true,"colors":{"higherChapter":"transparent","highlights":["rgba(82, 190, 90, 0.6)","rgba(107, 177, 95, 0.6)","rgba(55, 168, 61, 0.6)"],"lowerChapter":"rgba(180, 102, 75, 0.5)","nextChapter":"rgba(104, 115, 251, 0.4)","openedChapter":"rgba(28, 135, 141, 0.4)"},"confirmChapter":false,"errorNotifications":true,"favoriteLanguage":"all","groupTitlesInLists":true,"hideHigher":false,"hideLast":true,"hideLower":true,"highlight":true,"linkToServices":true,"mainService":"mal","mdUpdateSyncDex":true,"noReloadStatus":true,"notifications":true,"originalThumbnail":false,"overviewMainOnly":true,"progressInThumbnail":true,"saveOnlyHigher":true,"saveOnlyNext":false,"saveOpenedChapters":true,"separateLanguages":true,"services":["mal","mu","al"],"subVersion":4,"thumbnail":true,"thumbnailMaxHeight":80,"tokens":{"anilistToken":"set"},"updateMD":true,"updateOnlyInList":false,"useMochi":true,"version":0.1}}`

**Comment by lol480phuh** [comment]
Update: I don't know if it's because some time has passed, but some of the chapters are hidden now 

![image](https://user-images.githubusercontent.com/52804334/103152578-a76d9380-4789-11eb-821d-a2433427fa02.png)

But for some manga (Mieruko-chan for example) I read the new chapter 15 mins ago but still no updates in the list.

![image](https://user-images.githubusercontent.com/52804334/103152593-e3085d80-4789-11eb-9f07-86b8ac22a5fb.png)

**Comment by Glagan** [comment]
Weird, if it's highlighted in the Title page it should work in the follow list, there is no error and another title is highlighted.  
Did you do anything between your screenshots and before it actually hide ? There should be no delay when something is saved.

Could you send me your exported SyncDex save so I can check what is saved ? You can upload it to PasteBin for example.

**Comment by lol480phuh** [comment]
Update 2: Komi and Mieruko are synced now (I refreshed the page 3-4 times for it to work, it showed two popups one for each series) 
Something like this :

![image](https://user-images.githubusercontent.com/52804334/103154053-68ddd600-4795-11eb-9646-06d823748172.png)



Now the same is happening with Takagi-san and Kusuriya and some other series that I read their latest chapters before installing the extension, they're not syncing, even though some other manga (Deadpool was synced at the very beginning and I read it last night before downloading SyncDex)


![image](https://user-images.githubusercontent.com/52804334/103152743-30d19580-478b-11eb-8cc7-3befc738d1f0.png)

Here's the SyncDex save ( I never used Pastebin so if I need to re-upload let me know):

https://pastebin.com/Pr9EiRiM

Update 3: I noticed it recognize the chapter as read, but doesn't recognize it as " The Latest", Unless I click "Set as latest" and refresh nothing will update. hope this is enough information.

**Comment by Glagan** [comment]
It's weird, your save have *Soredemo Ayumu...* with chapter 83 in your save, and it's the same for the other titles, I also cannot reproduce this issue, and with the same options as you I don't see how only some chapters will be highlighted but others not...  
Also using the Set as latest button only does the same as when you read, so it should already be up to date if you read it...

Edit: Are you seeing notifications on the bottom left with ``[Synced]`` for each services, and are icons on the right changing colors then going green ?

**Comment by lol480phuh** [comment]
The notifications aren't showing up when reading the chapters (Which was a thing in MMD) see screenshot about _Kumo desu ga_ I read a new chapter, but no notifications are showing up. 
![image](https://user-images.githubusercontent.com/52804334/103154579-924c3100-4798-11eb-8064-16dcdca8cef0.png)

and the notification only shows up once I'm on the `follows` page after clicking `set as latest`

After reading it, no changes

![image](https://user-images.githubusercontent.com/52804334/103154640-08509800-4799-11eb-94c8-8f81897e4d38.png)


After clicking `set as latest`

![image](https://user-images.githubusercontent.com/52804334/103154670-28805700-4799-11eb-8db9-9445e4009623.png)

**Comment by Glagan** [comment]
You should see a notification when reading if you enabled it, and you did enable it (it's on by default), so there's probably an error when you read, I'll look if I can see the problem.

**Comment by lol480phuh** [comment]
I believe it's already enabled (if you mean the Save opened chapters option) 

![image](https://user-images.githubusercontent.com/52804334/103154769-24a10480-479a-11eb-9c4e-603483ee966c.png)

so chances are there's an error when opening a chapter, I'll try reinstalling the extension and update if anything happens.

edit: Reinstalled but nothing's changed :"(

take your time solving whatever errors are happening, and know that your extension (and MMD especially ) is the only reason I'm able to read on desktop, so thank you for your hard work <3 !!

**Comment by Glagan** [comment]
It should be fixed and the highlight too in the next version, you can close this issue if you don't have the problem anymore in version ``0.1.5``.

**Comment by lol480phuh** [comment]
Thank you for your hard work, the problem is gone in the new `0.1.5` version. <3
