### ISSUE TITLE
i need help with imports

### ISSUE THREAD

**Issue by Pancakes0** [Glagan/SyncDex#8]
it says: "It is not recommended to import from MyMangaDex only, since your score, start/end dates, status, and the name of each Title will be missing.
A better option is to make sure your MyAnimeList is up to date and import from MyAnimeList."

so i did. but i cant select .xml.gz meaning i cant start importing? 
also a question is syncdex replacing mmd? thanks

**Comment by Pancakes0** [comment]
wait no im dumb. nvm i tried importing mal on mmd sorry

**Comment by Glagan** [comment]
SyncDex will probably replace MMD since it has the same features but more.
