### ISSUE TITLE
removal of glowing green buttons [REQUEST]

### ISSUE THREAD

**Issue by Pancakes0** [Glagan/SyncDex#9]
![Screen Shot 2020-12-26 at 9 51 38 PM](https://user-images.githubusercontent.com/73923883/103152626-c50c1e80-47c4-11eb-89cb-b3b40db8e07b.png)

buttons that turn of glow when nothing is wrong but glows red when something is wrong. 
not that i mind but it is kind of distracting imo. edit button is useful though, not needing to go back to the manga page to edit entries.

**Comment by Glagan** [comment]
I can put that behind an option if that really bothers you.  
Do you want all buttons (except Edit) gone or is it just the colors (when it's done, not loading) ?

**Comment by Pancakes0** [comment]
yes pleasee! just the colours would be fine for me personally. thank youu

**Comment by Glagan** [comment]
I added a ``Remove icons green shadow`` option under the **Updates** category, and it's disabled by default so you need to enable it.

If it's not exactly what you expected, feel free to re-open this issue ;)

**Comment by Pancakes0** [comment]
nope it perfect! thank you~ 👍
